name: Deploy to GitHub Pages

on:
  push:
    branches:
      - cloud_version # Desencadena el flujo de trabajo cada vez que se hace push a la rama 'main'
  workflow_dispatch: # Permite ejecutar el flujo de trabajo manualmente desde la pestaña de Actions en GitHub

permissions:
  contents: write # Permite escribir contenidos en el repositorio
  pages: write # Permite escribir páginas en GitHub Pages
  id-token: write # Permite escribir tokens de identificación

jobs:
  changes:
    runs-on: ubuntu-latest # Ejecuta este trabajo en un contenedor Ubuntu más reciente
    outputs:
      src: ${{ steps.changes.outputs.src }} # Salida para cambios en archivos fuente
      infra: ${{ steps.changes.outputs.infra }} # Salida para cambios en la infraestructura
    steps:
      - uses: actions/checkout@v4 # Clona el repositorio
      - uses: dorny/paths-filter@v3 # Filtra cambios en los archivos especificados
        id: changes
        with:
          base: origin/cloud-test # Comparar con el último estado de cloud-test
          filters: |
            src:
              - 'src/cv_info/cv.js' # Archivos que se monitorizan para cambios
              - 'src/pages/en/cv.astro'
              - 'src/pages/es/cv.astro'
  generate-pdf:
    if: ${{ needs.changes.outputs.src == 'true' }} # Este trabajo se ejecuta solo si hay cambios en los archivos fuente especificados
    needs: [changes] # Este trabajo depende del trabajo 'changes'
    runs-on: ubuntu-latest # Ejecuta este trabajo en un contenedor Ubuntu más reciente
    env:
      PROD: ${{ false }} # Define la variable de entorno PROD
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Clona el repositorio en la rama actual
      - name: Install dependencies
        run: npm install # Instala las dependencias necesarias
      - name: Build site with Astro
        run: npm run build # Construye el sitio
      - name: Start Astro preview server in the background
        run: nohup npm run preview & # Levanta el servidor en segundo plano
      - name: Wait for the preview server to start
        run: sleep 5 # Espera unos segundos para que el servidor se inicie correctamente
      - name: Generate PDFs
        run: npm run GPDF # Genera los PDFs usando la vista del servidor
      - name: Stop Astro preview server
        run: kill $(lsof -t -i:4321) # Detiene el servidor en el puerto predeterminado de Astro (3000)
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} # Utiliza el token de GitHub para autenticarse
        uses: stefanzweifel/git-auto-commit-action@v5 # Realiza commit y push de los cambios
        with:
          branch: cloud_version
          commit_message: Update PDFs # Mensaje del commit
